# TensorFlow 2.0 Course

---

In [2]:
import tensorflow as tf
import numpy as np

## **Tensors**

> "A ``Tensor`` is a generalization os vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents ``tensors`` as n-dimensioanl arrays of datatypes." ([Tensor Guide: tensorflow.org](https://www.tensorflow.org/guide/tensor))

- Os **Tensores** são um dos principais aspectos do TensorFlow. Eles são o principal objeto que é passado e manipulado através do programa. Cada **Tensor** representa uma computação parcialmente definida que eventualmente vai produzir um valor. Os programas com TensorFlow funcionam construindo um gráfico de objetos `Tensor` que detalha como os **Tensors** estão relacionados. Rodando diferentes partes de um gráfico permite gerar resultados.

> Cada `Tensor` tem um **_tipo de dados_** e um **_formato_**.

**Data Types Inclue**: `float32`, `int32`, `string` and others.
**Shape** (formato): Represents the dimension of data.


---

### Creating **Tensors**

In [4]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

- Scalar Value: One Value
- Verctor Value: More than one value
- Matrices: Scale


### Rank/Degree of Tensors

> Another word for Rank is Degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a _tensor of rank 0_, also known as a scalar.

- Now we'll create some `Tensors` of higher degrees/ranks.

In [7]:
rank_1_tensor = tf.Variable(['test'], tf.string)
rank_2_tensor = tf.Variable([['test', 'ok'], ['test', 'yes']], tf.string)

- Ver o rank/degree do `Tensor`

**_Função:_** `tf.rank(variável_tensor)`

In [9]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [10]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [8]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

- Ver o formato / shape do tensor

**_Função:_** `tensor_variable.shape`

In [13]:
rank_2_tensor.shape

TensorShape([2, 2])

In [14]:
number.shape

TensorShape([])

In [15]:
rank_1_tensor.shape

TensorShape([1])